//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaliSaha.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class KiralanmışSahaTablo
    {
        public int KSID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> SahaID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> SaatBaslangic { get; set; }
        public Nullable<int> SemtID { get; set; }
    
        public virtual KullaniciGirisTablo KullaniciGirisTablo { get; set; }
        public virtual SahaTablo SahaTablo { get; set; }
        public virtual SemtTablo SemtTablo { get; set; }
    }
}
