//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaliSaha.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class OyuncuTablo
    {
        public int OyuncuID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public string OyuncuAdi { get; set; }
        public string OyuncuSoyadi { get; set; }
        public int MevkiID { get; set; }
        public string OyuncuTelefon { get; set; }
        public bool Durum { get; set; }
        public Nullable<bool> OyuncuSilmedurum { get; set; }
        public int SahaID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> MacSaati { get; set; }
    
        public virtual KullaniciGirisTablo KullaniciGirisTablo { get; set; }
        public virtual MevkiTablo MevkiTablo { get; set; }
        public virtual SahaTablo SahaTablo { get; set; }
    }
}
