//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaliSaha.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakımTablo
    {
        public int TakımID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public string TakımAdı { get; set; }
        public string Telefon { get; set; }
        public int SemtID { get; set; }
        public bool TakımDurum { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public bool TakımSilmedurum { get; set; }
        public int SahaID { get; set; }
        public Nullable<int> MacSaati { get; set; }
    
        public virtual KullaniciGirisTablo KullaniciGirisTablo { get; set; }
        public virtual SahaTablo SahaTablo { get; set; }
        public virtual SemtTablo SemtTablo { get; set; }
    }
}
